import { StyleSheet } from 'react-native'
import { colors, spacing, radius, type } from '../../theme/theme'

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bgBase },

  searchRow: { flexDirection: 'row', gap: spacing.xs, marginHorizontal: spacing.md },
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    minHeight: 48,
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radius.md,
  },
  searchInput: { flex: 1, ...type.body, color: colors.textPrimary, paddingVertical: spacing.sm },
  manageBtn: {
    width: 48,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radius.md,
  },

  chipScroll: { flexGrow: 0 },
  chips: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, gap: spacing.xs },
  chip: {
    minHeight: 40,
    paddingHorizontal: spacing.md,
    justifyContent: 'center',
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.bgSurface,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { ...type.label, color: colors.textPrimary },
  chipTextActive: { color: colors.onPrimary, fontWeight: '700' },

  grid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: spacing.md, gap: spacing.sm },
  tile: {
    width: '48%',
    flexGrow: 1,
    backgroundColor: colors.bgSurface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    padding: spacing.sm,
    minHeight: 150,
  },
  tileSelected: { borderColor: colors.primary, borderWidth: 2, padding: spacing.sm - 1 },
  tileDisabled: { opacity: 0.55 },
  tileTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.xs },
  tileIcon: { width: 40, height: 40, borderRadius: radius.sm, backgroundColor: colors.accentTint, alignItems: 'center', justifyContent: 'center' },
  qtyBadge: { minWidth: 28, height: 28, borderRadius: 14, paddingHorizontal: 6, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  qtyBadgeText: { ...type.labelBold, color: colors.onPrimary },
  tileName: { ...type.bodyMedium, color: colors.textPrimary },
  tileSize: { ...type.caption, color: colors.textSecondary },
  tilePrice: { ...type.h2, color: colors.textPrimary, marginTop: spacing.xs },
  tileStock: { ...type.caption, color: colors.textSecondary, marginTop: 2 },
  tileWarn: { ...type.captionMedium, color: colors.errorDefault, marginTop: 2 },

  saved: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.successTint,
    borderRadius: radius.md,
    padding: spacing.sm,
  },
  savedText: { ...type.label, color: colors.secondary, flex: 1 },
  empty: { ...type.body, color: colors.textSecondary, paddingVertical: spacing.lg, textAlign: 'center', width: '100%' },

  cart: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.bgSurface,
    borderTopWidth: 1,
    borderTopColor: colors.borderDefault,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  cartHint: { ...type.label, color: colors.textSecondary, textAlign: 'center', paddingVertical: spacing.sm },
  cartHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 40 },
  cartTitle: { ...type.labelBold, color: colors.textPrimary },
  cartToggle: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  cartToggleText: { ...type.labelBold, color: colors.primary },
  cartList: { maxHeight: 240 },
  cartLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.borderDefault,
  },
  cartName: { ...type.label, color: colors.textPrimary },
  cartRecipe: { ...type.caption, color: colors.textSecondary },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  stepBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepQty: { ...type.bodyMedium, minWidth: 24, textAlign: 'center', color: colors.textPrimary },
  cartLineTotal: { ...type.labelBold, color: colors.textPrimary, minWidth: 64, textAlign: 'right' },

  recordBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    minHeight: 56,
    paddingHorizontal: spacing.md,
    marginTop: spacing.xs,
  },
  recordText: { ...type.bodyMedium, fontWeight: '700', color: colors.onPrimary },
  recordTotal: { ...type.h2, color: colors.onPrimary },
})
