import { StyleSheet } from 'react-native'
import { colors, spacing, radius, type, shadow, card } from '../../theme/theme'

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bgBase },
  scroll: { paddingTop: spacing.xs },
  toast: {
    position: 'absolute', left: 20, right: 20, zIndex: 99,
    backgroundColor: colors.inverseSurface, borderRadius: 12,
    flexDirection: 'row', alignItems: 'center', gap: spacing.xs,
    paddingHorizontal: spacing.md, paddingVertical: spacing.sm,
    ...shadow.md,
  },
  toastText: { ...type.label, color: colors.inverseOnSurface, flex: 1 },

  searchBar: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, paddingHorizontal: spacing.md, paddingBottom: spacing.sm, backgroundColor: colors.bgSurface, ...shadow.sm },
  searchInput: { flex: 1, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surfaceContainerLow, borderRadius: 8, paddingHorizontal: spacing.sm, height: 48, gap: spacing.xs },
  searchText: { flex: 1, ...type.body, color: colors.textPrimary },
  scanBtn: { width: 48, height: 48, borderRadius: 8, backgroundColor: colors.primaryContainer, alignItems: 'center', justifyContent: 'center' },

  categoryList: { paddingHorizontal: spacing.md, paddingTop: spacing.sm, paddingBottom: 4, gap: spacing.xs },
  categoryPill: { height: 36, paddingHorizontal: spacing.sm, borderRadius: 8, backgroundColor: colors.surfaceContainerLow, flexDirection: 'row', alignItems: 'center', gap: 4 },
  categoryPillActive: { backgroundColor: colors.accentTint, ...shadow.sm },
  categoryText: { ...type.label, color: colors.textSecondary },
  categoryTextActive: { ...type.labelBold, color: colors.primary },
  categoryDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.primary },

  gridHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.md, paddingTop: spacing.md, paddingBottom: spacing.xs },
  gridTitle: { ...type.labelBold, color: colors.textPrimary },
  gridHint: { ...type.caption, color: colors.textSecondary },

  grid: { flexDirection: 'row', flexWrap: 'wrap', paddingHorizontal: spacing.md, gap: spacing.sm },
  productCard: { width: '47.5%', ...card.base, padding: spacing.md },
  productCardDisabled: { opacity: 0.75 },
  productImageWrap: { height: 80, borderRadius: 8, backgroundColor: colors.surfaceContainerLow, marginBottom: spacing.xs, overflow: 'hidden', position: 'relative' },
  productImage: { width: '100%', height: '100%' },
  lockedOverlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(208,218,240,0.4)', alignItems: 'center', justifyContent: 'center' },
  productBadge: { position: 'absolute', top: 4, right: 4, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 9999 },
  productBadgeText: { fontSize: 10, fontWeight: '500', lineHeight: 14 },
  productName: { ...type.labelBold, color: colors.textPrimary },
  productCategory: { ...type.caption, color: colors.textSecondary, marginTop: 2 },
  productFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.xs },
  productPrice: { ...type.h2, color: colors.textPrimary },
  addBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.accentTint, alignItems: 'center', justifyContent: 'center' },
  addBtnText: { fontSize: 20, fontWeight: '700', color: colors.primary, lineHeight: 24 },
  disabledWarning: { flexDirection: 'row', alignItems: 'flex-start', gap: 4, backgroundColor: colors.errorTint, borderRadius: 8, padding: 6, marginTop: 4 },
  disabledWarningText: { ...type.caption, color: colors.errorDefault, flex: 1 },

  drawer: { position: 'absolute', left: 0, right: 0, backgroundColor: colors.bgSurface, borderTopLeftRadius: 16, borderTopRightRadius: 16, ...shadow.md },
  drawerHandle: { paddingVertical: 10, paddingHorizontal: spacing.md, alignItems: 'center' },
  drawerPill: { width: 40, height: 4, borderRadius: 2, backgroundColor: colors.borderDisabled, marginBottom: 4 },
  drawerHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', width: '100%' },
  drawerTitle: { ...type.labelBold, color: colors.textPrimary },
  cartBadge: { backgroundColor: colors.accentTint, paddingHorizontal: 8, paddingVertical: 2, borderRadius: 9999 },
  cartBadgeText: { ...type.captionMedium, color: colors.primary },
  drawerToggleText: { ...type.caption, color: colors.textSecondary },
  drawerBody: { maxHeight: 200, paddingHorizontal: spacing.md },

  cartItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surfaceContainerLow, borderRadius: 12, padding: spacing.sm, marginBottom: spacing.sm, gap: spacing.xs },
  cartItemName: { ...type.labelBold, color: colors.textPrimary },
  cartItemUnit: { ...type.caption, color: colors.textSecondary },
  stepper: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.bgSurface, borderRadius: 8, ...shadow.sm },
  stepperBtn: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' },
  stepperQty: { width: 32, textAlign: 'center', ...type.labelBold, color: colors.textPrimary },
  cartItemTotal: { width: 64, textAlign: 'right', ...type.labelBold, color: colors.textPrimary },

  recipeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.bgSurface, borderRadius: 8, padding: spacing.xs, marginBottom: 4 },
  recipeLabel: { ...type.captionMedium, color: colors.primary },
  recipeText: { ...type.caption, color: colors.textSecondary, paddingHorizontal: spacing.md, paddingBottom: spacing.xs },

  saleTotal: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderTopWidth: 1, borderTopColor: colors.borderDefault },
  saleSummaryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.xs },
  saleSummaryLabel: { ...type.caption, color: colors.textSecondary },
  saleTotal2: { ...type.h1, color: colors.textPrimary },
  cashPill: { backgroundColor: colors.successTint, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  cashPillText: { ...type.captionMedium, color: colors.secondary },
  confirmBtn: { backgroundColor: colors.primary, height: 48, borderRadius: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs },
  confirmBtnText: { ...type.labelBold, color: colors.onPrimary },
})
