import { StyleSheet } from 'react-native'
import { colors, spacing, radius, type } from '../../theme/theme'

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bgBase },
  scroll: { paddingHorizontal: spacing.md, paddingTop: spacing.xs },

  intro: { ...type.body, color: colors.textPrimary, marginBottom: spacing.md },

  budgetCard: {
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  budgetRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  budgetLabel: { ...type.bodyMedium, color: colors.textPrimary },
  budgetInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    minHeight: 48,
    minWidth: 140,
  },
  budgetCurrency: { ...type.h2, color: colors.textSecondary, marginRight: 4 },
  budgetInput: { ...type.h2, color: colors.textPrimary, flex: 1, paddingVertical: spacing.xs },
  progressTrack: { height: 8, borderRadius: 4, backgroundColor: colors.surfaceContainer, marginTop: spacing.md, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 4 },
  budgetStatus: { ...type.label, marginTop: spacing.xs },

  list: {
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radius.md,
    overflow: 'hidden',
  },
  item: { padding: spacing.md },
  itemDivider: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.borderDefault },
  itemTop: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm },
  checkHit: { width: 44, height: 44, marginLeft: -10, marginTop: -10, alignItems: 'center', justifyContent: 'center' },
  checkbox: { width: 24, height: 24, borderRadius: 6, borderWidth: 2, borderColor: colors.borderDisabled, alignItems: 'center', justifyContent: 'center' },
  checkboxOn: { backgroundColor: colors.primary, borderColor: colors.primary },
  itemName: { ...type.bodyMedium, color: colors.textPrimary },
  itemOff: { color: colors.textSecondary, textDecorationLine: 'line-through' },
  itemQty: { ...type.caption, color: colors.textSecondary, marginTop: 2 },
  itemLevel: { ...type.captionMedium, marginTop: 2 },
  itemCost: { ...type.h2, color: colors.textPrimary },

  itemBottom: { flexDirection: 'row', alignItems: 'center', marginTop: spacing.xs, marginLeft: 46 },
  supplierText: { ...type.caption, color: colors.textSecondary, flex: 1 },
  linkHit: { minHeight: 40, justifyContent: 'center', paddingLeft: spacing.sm },
  link: { ...type.labelBold, color: colors.primary },

  options: { marginLeft: 46, marginTop: 4, borderRadius: radius.sm, backgroundColor: colors.bgBase },
  option: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, minHeight: 48, paddingHorizontal: spacing.sm },
  radio: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: colors.borderDisabled, alignItems: 'center', justifyContent: 'center' },
  radioOn: { borderColor: colors.primary },
  radioDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary },
  optionName: { ...type.label, color: colors.textPrimary, flex: 1 },
  optionPrice: { ...type.labelBold, color: colors.textPrimary },

  whyToggle: { flexDirection: 'row', alignItems: 'center', gap: 2, minHeight: 40, marginLeft: 46 },
  why: { ...type.label, color: colors.textPrimary, marginLeft: 46, lineHeight: 20 },

  regularRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },

  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.bgSurface,
    borderTopWidth: 1,
    borderTopColor: colors.borderDefault,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  footerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: spacing.xs },
  footerLabel: { ...type.label, color: colors.textSecondary },
  footerTotal: { ...type.h2, color: colors.textPrimary },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    minHeight: 56,
  },
  saveBtnOff: { backgroundColor: colors.borderDisabled },
  saveBtnDone: { backgroundColor: colors.secondary },
  saveText: { ...type.bodyMedium, fontWeight: '700', color: colors.onPrimary },
})
